package edu.sc.seis.fissuresUtil.bag;

import junit.framework.TestCase;

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class DistAzTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  DistAz distaz = null;
  // JUnitDoclet end class
  
  public DistAzTest(String name) {
    // JUnitDoclet begin method DistAzTest
    super(name);
    // JUnitDoclet end method DistAzTest
  }
  
  public edu.sc.seis.fissuresUtil.bag.DistAz createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
      return new edu.sc.seis.fissuresUtil.bag.DistAz(0, 0, 90, 0);
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    distaz = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    distaz = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testMain() throws Exception {
    // JUnitDoclet begin method main
    // JUnitDoclet end method main
  }
  
  public void sueTest() {
      DistAz dz = new edu.sc.seis.fissuresUtil.bag.DistAz(29.331, -113.697, 29.331, -113.697);
      assertEquals(0, dz.getDelta(), 0.000001);
  }
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(DistAzTest.class);
    // JUnitDoclet end method testcase.main
  }
}
