package edu.sc.seis.fissuresUtil.bag;

import junit.framework.TestCase;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class RMeanTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  edu.sc.seis.fissuresUtil.bag.RMean rmean = null;
  // JUnitDoclet end class
  
  public RMeanTest(String name) {
    // JUnitDoclet begin method RMeanTest
    super(name);
    // JUnitDoclet end method RMeanTest
  }
  
  public edu.sc.seis.fissuresUtil.bag.RMean createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new edu.sc.seis.fissuresUtil.bag.RMean();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    rmean = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    rmean = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testApply() throws Exception {
    // JUnitDoclet begin method apply
    // JUnitDoclet end method apply
  }
  
  public void testRemoveMean() throws Exception {
    // JUnitDoclet begin method removeMean
    // JUnitDoclet end method removeMean
  }
  
  public void testRemoveMeanInPlace() throws Exception {
    // JUnitDoclet begin method removeMeanInPlace
    // JUnitDoclet end method removeMeanInPlace
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(RMeanTest.class);
    // JUnitDoclet end method testcase.main
  }
}
