package edu.sc.seis.fissuresUtil.bag;

import junit.framework.TestCase;
// JUnitDoclet begin import
import edu.sc.seis.fissuresUtil.bag.Cut;
import edu.iris.Fissures.model.*;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CutTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  edu.sc.seis.fissuresUtil.bag.Cut cut = null;
  // JUnitDoclet end class
  
  public CutTest(String name) {
    // JUnitDoclet begin method CutTest
    super(name);
    // JUnitDoclet end method CutTest
  }
  
  public edu.sc.seis.fissuresUtil.bag.Cut createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
      MicroSecondDate now = new MicroSecondDate();
      return new edu.sc.seis.fissuresUtil.bag.Cut(now.subtract(new TimeInterval(1, UnitImpl.MINUTE)), now);
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    cut = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cut = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testApply() throws Exception {
    // JUnitDoclet begin method apply
    // JUnitDoclet end method apply
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CutTest.class);
    // JUnitDoclet end method testcase.main
  }
}
