package edu.sc.seis.fissuresUtil.bag;

import junit.framework.TestCase;
// JUnitDoclet begin import
import edu.sc.seis.fissuresUtil.bag.ResponseGain;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class ResponseGainTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  edu.sc.seis.fissuresUtil.bag.ResponseGain responsegain = null;
  // JUnitDoclet end class
  
  public ResponseGainTest(String name) {
    // JUnitDoclet begin method ResponseGainTest
    super(name);
    // JUnitDoclet end method ResponseGainTest
  }
  
  public edu.sc.seis.fissuresUtil.bag.ResponseGain createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
      return new edu.sc.seis.fissuresUtil.bag.ResponseGain((edu.iris.Fissures.IfNetwork.NetworkDC)null);
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    responsegain = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    responsegain = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testApply() throws Exception {
    // JUnitDoclet begin method apply
    // JUnitDoclet end method apply
  }
  
  
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ResponseGainTest.class);
    // JUnitDoclet end method testcase.main
  }
}
