package edu.sc.seis.fissuresUtil.freq;

import junit.framework.TestCase;
// JUnitDoclet begin import
import edu.sc.seis.fissuresUtil.freq.Cmplx;
// JUnitDoclet end import

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class CmplxTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
    edu.sc.seis.fissuresUtil.freq.Cmplx cmplx = null;
  // JUnitDoclet end class
  
  public CmplxTest(String name) {
    // JUnitDoclet begin method RTrendTest
    super(name);
    // JUnitDoclet end method RTrendTest
  }
  
  public edu.sc.seis.fissuresUtil.freq.Cmplx createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
      return new edu.sc.seis.fissuresUtil.freq.Cmplx();
    // JUnitDoclet end method testcase.createInstance
  }
  
  protected void setUp() throws Exception {
      // JUnitDoclet begin method testcase.setUp
      super.setUp();
      cmplx = createInstance();
      // JUnitDoclet end method testcase.setUp
  }
  
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    cmplx = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  public void testCorrelate() throws Exception {
    // JUnitDoclet begin method apply
      float[] inA = new float[32];
      float[] inB = new float[32];
      inA[5] = 1;
      inB[3] = 1;
      float[] out = Cmplx.correlate(inA, inB);
      for ( int i=0; i<inA.length; i++) {
	  System.out.println(inA[i]+"  "+inB[i]+"  "+out[i]);
      } // end of for ()
      
      assertEquals("float", 1.0f, out[2], 0.0000001);
    // JUnitDoclet end method apply
  }
  
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * Method testVault is supposed to be empty.
  */
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CmplxTest.class);
    // JUnitDoclet end method testcase.main
  }
}
